### ISSUE TITLE
Regarding merged EPIC-Kitchens features

### ISSUE THREAD

**Issue by Anirudh257** [JacobChalk/TIM#15]
Hi, thanks for open-sourcing your excellent work. I wanted to replicate the results but it is computationally expensive. Would it be possible for you to share the merged OMNIVORE and VideoMAE features?

**Comment by JacobChalk** [comment]
Hi,

We are unable to share the data as we have nowhere to store it due to its size unfortunately.

**Comment by Anirudh257** [comment]
Thanks for the prompt response, @JacobChalk!
