### ISSUE TITLE
Can not find the files

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#16]
When I extract feature of the epic/AVE/Perception test,
I can not find the files of the  :pickle file that has start and end time stamp for frame-level features
SO how can I get the files ?
THANK YOU !

**Comment by JacobChalk** [comment]
Hi,

The files can be found here:

https://www.dropbox.com/scl/fi/xs6muwf67a5h9ql30jart/annotations.zip?rlkey=iw6b4w9n4brcpvygoksmrvf4n&st=j6c1exut&dl=0

You can find the timestamps for the frame level features in:

`annotations/<DATASET>/<DATASET>_1_second_<SPLIT>_feature_times.pkl`

**Comment by MuXiangWen** [comment]
THANK YOU VERY MUCH ！！
YOU ARE SO GREATTTTT！！！
