### ISSUE TITLE
how to split the AVE data into train/test/val  and i download the data  from https://drive.google.com/open?id=1FjKwe79e0u96vdjIVwfRQ1V6SoDHe7kK

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#18]

**Comment by MuXiangWen** [comment]
and Can i use the feature provided by the https://github.com/YapengTian/AVE-ECCV18

<img width="827" alt="image" src="https://github.com/JacobChalk/TIM/assets/94733207/26f6837b-a35b-4a84-8b0b-58f5c0e0fb1c">

**Comment by JaesungHuh** [comment]
Of course you can use it. We actually tried it and get the result of 79% accuracy, as reported in Table 4 in our [paper](https://arxiv.org/pdf/2404.05559).

However, you need to build the pickle files for features and labels to run our script based on what they've provided, using additional metadata files they provided in the website.
