### ISSUE TITLE
parameters question

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#19]
when i use the following to extract audio features, the setting of 'TRAIN.ENABLE' and TEST.ENABLE", When should these two parameters be set to True or False?

python tools/run_net.py 
--cfg /path/to/configs/PERCEPTION/SLOWFAST_R50.yml \
NUM_GPUS <num_gpus> \
OUTPUT_DIR /path/to/output/dataset_split \
PERCEPTION.AUDIO_DATA_DIR /path/to/PERCEPTION_audio_files \
PERCEPTION.TEST_LIST /path/to/PERCEPTION_feature_interval_times \
TRAIN.ENABLE False \
TEST.ENABLE True \
TEST.CHECKPOINT_FILE_PATH /path/to/pretrained_auditory_slowfast \
TEST.NUM_FEATURES <num_features>

**Comment by JaesungHuh** [comment]
Those are the parameters when we used to train / test the model. However, if you are simply extracting the features, those are not used so you could keep them like that. I'll remove those in the future for avoiding confusions.

**Comment by MuXiangWen** [comment]
> Those are the parameters when we used to train / test the model. However, if you are simply extracting the features, those are not used so you could keep them like that. I'll remove those in the future for avoiding confusions.

"keep them like that" means do not set them?(ignore them in command) like this:

python tools/run_net.py
--cfg /path/to/configs/PERCEPTION/SLOWFAST_R50.yml
NUM_GPUS <num_gpus>
OUTPUT_DIR /path/to/output/dataset_split
PERCEPTION.AUDIO_DATA_DIR /path/to/PERCEPTION_audio_files
PERCEPTION.TEST_LIST /path/to/PERCEPTION_feature_interval_times
TEST.CHECKPOINT_FILE_PATH /path/to/pretrained_auditory_slowfast
TEST.NUM_FEATURES <num_features>

**Comment by JaesungHuh** [comment]
Actually you need to specify TEST.ENABLE False in either command or config file because of [this](https://github.com/JacobChalk/TIM/blob/138fd0629f90d132458b149e5ef76422f16b49a8/feature_extractors/auditory_slowfast/tools/run_net.py#L20) assert line.

Please set TRAIN.ENABLE False and TEST.ENABLE True at the moment. 
We'll remove that parameters in the future.
