### ISSUE TITLE
video feature problem

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#21]
when i use the following command to extract perception_test video validatioin feature, there is nothing in my OUTPUT_DIR:

```
CUDA_VISIBLE_DEVICES=6,7 python tools/run_net.py 
--cfg /data/nvme2/dky/lc/TIM/feature_extractors/omnivore/configs/PERCEPTION_TEST/OMNIVORE_feature.yaml \
NUM_GPUS 2 \
OUTPUT_DIR /data/hdd/lishenshen/TIMfeature_data/perception_test-feature/val_v \
PERCEPTION.VISUAL_DATA_DIR /data/hdd/lishenshen/TIMframe_data/perception_test-frame/val_v \
PERCEPTION.TEST_LIST /data/nvme2/dky/lc/TIM/annotations/Perception_Test/Perception_Test_1_second_validation_feature_times.pkl \
TEST.BATCH_SIZE 4 \
TEST.ENABLE True \
TEST.NUM_FEATURES 1

```
and the command output is :(cur_iter is from 0 to 296828)

`[INFO: logging.py:   76]: json_stats: {"cur_iter": "296824", "eta": "0:00:00", "split": "test_iter", "time_diff": 0.025835}
[INFO: logging.py:   76]: json_stats: {"cur_iter": "296825", "eta": "0:00:00", "split": "test_iter", "time_diff": 0.025927}
[INFO: logging.py:   76]: json_stats: {"cur_iter": "296826", "eta": "0:00:00", "split": "test_iter", "time_diff": 0.026084}
[INFO: logging.py:   76]: json_stats: {"cur_iter": "296827", "eta": "0:00:00", "split": "test_iter", "time_diff": 0.025958}
[INFO: logging.py:   76]: json_stats: {"cur_iter": "296828", "eta": "0:00:00", "split": "test_iter", "time_diff": 0.025732}
[WARNING: meters.py:   95]: clip count tensor([1, 1, 1,  ..., 1, 1, 1]) ~= num clips 1
[WARNING: meters.py:  100]: tensor([1, 1, 1,  ..., 1, 1, 1])
WARNING:omnivore.utils.meters:clip count tensor([1, 1, 1,  ..., 1, 1, 1]) ~= num clips 1
WARNING:omnivore.utils.meters:tensor([1, 1, 1,  ..., 1, 1, 1])`

**Comment by JaesungHuh** [comment]
OMG. Thank you very much for reporting this.

There used to be an unknown error that the script only allows to save the features only for Epic and AVE. [here](https://github.com/JacobChalk/TIM/blob/896b546a25e029385e43076c2f29b0088d9b2f74/feature_extractors/omnivore/tools/extract_features.py#L128
)

I fixed the problem in current branch now. I apologize for the inconvenience.

BW,
Jaesung

**Comment by MuXiangWen** [comment]
> OMG. Thank you very much for reporting this.
> 
> There used to be an unknown error that the script only allows to save the features only for Epic and AVE. [here](https://github.com/JacobChalk/TIM/blob/896b546a25e029385e43076c2f29b0088d9b2f74/feature_extractors/omnivore/tools/extract_features.py#L128)
> 
> I fixed the problem in current branch now. I apologize for the inconvenience.
> 
> BW, Jaesung

Thank You.
and there is another problem:  error: RuntimeError: Trying to resize storage that is not resizable
when i set  NUM_GPUS 2 TEST.BATCH_SIZE 2 ,the command can run but need a lot of time,
when i set   NUM_GPUS 2 TEST.BATCH_SIZE 4 or  NUM_GPUS 4 TEST.BATCH_SIZE 8, it will be error: RuntimeError: Trying to resize storage that is not resizable
and when i set num_works=0 in configure file:OMNIVORE_feature.yaml  ,  NUM_GPUS 2 TEST.BATCH_SIZE 4 ,it will be error :RuntimeError: stack expects each tensor to be equal size,but got ......
