### ISSUE TITLE
EPIC_SOUNDS data problems

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#23]
i have got the HDF5 file of EPIC_SOUNDS, but how to split it into train test and validation?

**Comment by JacobChalk** [comment]
Hi,

Information on the EPIC-Sounds splits can be found [here](https://github.com/epic-kitchens/epic-sounds-annotations). We also have annotations compatible with TIM [here](https://www.dropbox.com/scl/fi/xs6muwf67a5h9ql30jart/annotations.zip?rlkey=iw6b4w9n4brcpvygoksmrvf4n&st=j6c1exut&dl=0).

To obtain the samples for a specific video ID in python, you need to do `samples = audio_dataset[video_id][()]` where `audio_dataset` is the read in HDF5 file. See the baseline code [here](https://github.com/epic-kitchens/epic-sounds-annotations/blob/main/src/slowfast/datasets/epicsounds.py) for more details.
