### ISSUE TITLE
can not find requirement.txt

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#24]
Hi
when i extract audio feature, in the feature_extractors/auditory_slowfast directory, i can not find the requirement.txt, so i can not set the conda enviroment following the commands:
<img width="578" alt="image" src="https://github.com/JacobChalk/TIM/assets/94733207/56dfdd5a-33b6-4bb1-a414-71958dfc52d1">

**Comment by JacobChalk** [comment]
Hi,

You can use the same requirements.txt as in the `omnivore` feature extractor folder. We will copy over the file to auditory_slowfast to avoid further confusion.
