### ISSUE TITLE
parameter problems

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#25]
when i want to validata TIM following the TIM/detection/README.md, as for the part :evaluate Perception Test Action, using the following command:
<img width="907" alt="image" src="https://github.com/JacobChalk/TIM/assets/94733207/9b87eb39-d59d-4958-98ff-fbd4df819074">

i have two questions:
first:  what is the --visual_input_dim? how can i know?
second : the path of the pretrained_model is  /path/to/perception_test_action_pth.tar ?(i mean use the .tar file directly?)

**Comment by JacobChalk** [comment]
Hi,

1. As shown in the commend, your `--visual_input_dim` is the channel size of the visual features. This will vary depending on which features you extract, though if you have copied ours, for Omnivore/VideoMAE it is 1024. For the combination of them, it is 2048. In future, you can verify any features you extract by simply loading one of the extracted features for the video, outputting the shape of the bumpy array and checking the final dimension
2. Correct, the path is directly to the .pth.tar file. The intrinsics of `torch.load()` will handle the .tar extension, so you do not need to worry about this.
