### ISSUE TITLE
Video feature extraction error

### ISSUE THREAD

**Issue by hongminglin08** [JacobChalk/TIM#3]
When I extract the test and validation sets for the AVE dataset in omnivore, the following error occurs：
validation set:
![image](https://github.com/JacobChalk/TIM/assets/52478955/c3f5e515-ce7a-4f6d-9b68-ec5a3c6451a5)
![image](https://github.com/JacobChalk/TIM/assets/52478955/cc4512f6-0a94-4ae2-b12f-59ddf62ba154)

test set:
![image](https://github.com/JacobChalk/TIM/assets/52478955/281fe296-2de8-449a-9505-d77cb6bb9ded)
![image](https://github.com/JacobChalk/TIM/assets/52478955/9bd8ebf3-83a9-472f-b7dd-ebdc6ae01a83)

**Comment by JaesungHuh** [comment]
Thank you for reporting this. 

I changed the scaling code while loading frames for AVE. 

The modified scaling function is reflected in [here](https://github.com/JacobChalk/TIM/blob/80c83220074956ceb4d6c3283d06a954b6b101ae/feature_extractors/omnivore/omnivore/datasets/ave.py#L128)

Please pull the repository or clone the code again and rerun it.

**Comment by hongminglin08** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月17日(星期五) 晚上9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JacobChalk/TIM] Video feature extraction error (Issue #3)














 
Thank you for reporting this.
 
I changed the scaling code while loading frames for AVE.
 
The modified scaling function is reflected in here
 
Please pull the repository or clone the code again and rerun it.
