### ISSUE TITLE
pretrained_model can not be found

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#32]
hi,
Thank you very much for [this Issue](https://github.com/JacobChalk/TIM/issues/30), 
But there still be some questions: 
when i extract video feature using command in the /omnivore/Readme.md , i can not find the pretrained models to extract video feature, Could you provide the pretrained models? 
Thank you Again!

**Comment by JacobChalk** [comment]
Hi, 

The pre-trained models are provided by the Omnivore authors themselves [here](https://github.com/JacobChalk/TIM/blob/5009d4b2663117e94c1aed2883fc449f765d03de/feature_extractors/omnivore/omnivore/models/omnivore_model.py#L74). Where the pre-trained model that is used corresponds to the MODEL.ARCH parameter in the [config file](https://github.com/JacobChalk/TIM/blob/5009d4b2663117e94c1aed2883fc449f765d03de/feature_extractors/omnivore/configs/EPIC-KITCHENS/OMNIVORE_feature.yaml#L11C3-L11C28).

Note this relies on internet access to use. If you are unable to access the internet while setting up the model, you can download the weights from one of the relevant links and then comment out [L119-121](https://github.com/JacobChalk/TIM/blob/5009d4b2663117e94c1aed2883fc449f765d03de/feature_extractors/omnivore/omnivore/models/omnivore_model.py#L119) in `omnivore_model.py`, replacing it with `checkpoint = torch.load(/path/to/downloaded_checkpoint.torch, map_location="cpu")` to load the local version instead. 

Also note we have updated the necessary config files to reflect the change for Perception, so this should now be done automatically.
