### ISSUE TITLE
Regarding the Two Annotation Sources

### ISSUE THREAD

**Issue by lin-nie** [JacobChalk/TIM#33]
Hello, thank you very much for providing such an outstanding and impressive model. I am currently attempting to reproduce your results.

 would like to understand why there are two different sources for obtaining the annotations: 1) one provided through the official channel: [https://github.com/epic-kitchens/epic-kitchens-100-annotations](https://github.com/epic-kitchens/epic-kitchens-100-annotations), and 2) the other provided in your TIM GitHub project: [https://www.dropbox.com/scl/fi/xs6muwf67a5h9ql30jart/annotations.zip?rlkey=iw6b4w9n4brcpvygoksmrvf4n&e=1&st=j6c1exut&dl=0](https://www.dropbox.com/scl/fi/xs6muwf67a5h9ql30jart/annotations.zip?rlkey=iw6b4w9n4brcpvygoksmrvf4n&e=1&st=j6c1exut&dl=0).

Could you please explain the differences between the annotations obtained from these two sources?

And also, when I extracted features using videoMAE and Omnivore, I used the first source, which is the [official annotation](https://github.com/epic-kitchens/epic-kitchens-100-annotations). I discovered later that you provided a second set of annotations. Could you please advise on how this might affect the extracted features? Should I re-extract the features using the [second set of annotations](https://www.dropbox.com/scl/fi/xs6muwf67a5h9ql30jart/annotations.zip?rlkey=iw6b4w9n4brcpvygoksmrvf4n&e=1&st=j6c1exut&dl=0)?

Really thank you for your help, wait for your message!

Nie

**Comment by JaesungHuh** [comment]
Hi lin-nie,

The annotations in the official channel are "action recognition" temporal segments, the segments that we want to recognise the human action.
The annotations in the Dropbox (*_feature_times.pkl) are start / end timestamps with the sliding window(stride 0.2 sec) 

For running TIM, you need to extract the features using the *_feature_times.pkl files, since TIM needs dense features of untrimmed videos. The annotations in the official channel are used for training TIM.

Jaesung

**Comment by lin-nie** [comment]
Hi, thank you very much for your prompt reply. Let me summarize your answer:

1. when **extracting features**, such as when using **VideoMAE or Omnivore** that you provide, we need to use _feature_times.pkl”. For example, the following two cases.

For **TIM-Omnivore backbone**:
![image](https://github.com/user-attachments/assets/71376336-36ad-465f-b0b6-89d9371b072a)


For **TIM-VideoMAE backbone:**
![image](https://github.com/user-attachments/assets/b9818de1-f99c-4213-af03-35345adecbf5)


2. when **training TIM**, we need to use the **annotation file provided by official channel**: [https://github.com/epic-kitchens/epic-kitchens-100-annotations](https://github.com/epic-kitchens/epic-kitchens-100-annotations), which corresponds to the instruction below:

For **TIM-recognition**:
![image](https://github.com/user-attachments/assets/ea1e261a-4fb4-4491-b04c-feb4803ed85e)

For **TIM-detection**:
![image](https://github.com/user-attachments/assets/5d63e8c5-7dea-4d8e-9eb5-e14fb1b32576)

Do I understand correctly? Jaesung, thank you very much!

Nie
2024.08.22

**Comment by JaesungHuh** [comment]
Yes.

In the second point, 
*_context_pickle --> you need to put the path of *_feature_times.pkl files.

**Comment by lin-nie** [comment]
So nice for your prompt reply, I got your point.

Thank you very much!

Jaesung, hope you have a nice day.

Nie
2024.08.22
