### ISSUE TITLE
Perception-test

### ISSUE THREAD

**Issue by Visitor-W** [JacobChalk/TIM#37]
Hello, I would like to ask how to fill in the PERCEPTION.TEST_LIST parameter when extracting features from the Perception-test/test dataset. Because I noticed that there is no interval file for TEST in the annotations file

**Comment by JacobChalk** [comment]
Hi,

You will need to create a feature time file similar to the ones for train and val. Specifically, you will need to create 1.1 second intervals, every 0.2 seconds for each video in the test set. So you will have a file similar to:

```[python]
   video_id         start_time       stop_time       start_frame       stop_frame
test_video_1            0.0            1.1          start_time*fps    stop_time*fps
test_video_1            0.2            1.3          start_time*fps    stop_time*fps
test_video_1            0.4            1.5          start_time*fps    stop_time*fps
     ...                ...            ...               ...              ...
test_video_n       vid_dur-1.1       vid_dur        start_time*fps    stop_time*fps
```

You can then pass this to the feature extractors to extract dense, overlapping features across all of the test videos. The two things you will need are the duration of each video in the test set, as well as their fps.

**Comment by Visitor-W** [comment]
I appreciate your detailed and clear explanation. Thank you very much for your help.
