### ISSUE TITLE
Perception Test/train/audio 

### ISSUE THREAD

**Issue by Visitor-W** [JacobChalk/TIM#38]
I'm sorry to bother you again. I have noticed that the video_5259.wav in the audio file of Perception Test/train downloaded from the official website is damaged. What should I do with it, please?

**Comment by JaesungHuh** [comment]
Hi!! 

I also noticed that so I re-extracted the audio file from the corresponding video file. You could also do that.

If you let me know your email, I'll send the file if you want.

Best wishes,
Jaesung

**Comment by Visitor-W** [comment]
Oh! I really appreciate it! My email is wzhao@bupt.edu.cn. I look forward to hearing from you
