### ISSUE TITLE
run this code on other datasets

### ISSUE THREAD

**Issue by hongminglin08** [JacobChalk/TIM#39]
If I wanted to run this code on other datasets, how would the following annotations be obtained? These include the feature time for intervals for training and valdiation splits, and the video metadata of the dataset.

**Comment by JaesungHuh** [comment]
Hi, I added the code I used to generate annotations of perception_test below.

Please change the paths and feel free to use them.

https://github.com/JacobChalk/TIM/blob/main/feature_extractors/make_framepickle.py

**Comment by hongminglin08** [comment]
> Hi, I added the code I used to generate annotations of perception_test below.
> 
> Please change the paths and feel free to use them.
> 
> https://github.com/JacobChalk/TIM/blob/main/feature_extractors/make_framepickle.py

Thanks! Is this the code to get Perception_Test_1_second_train_feature_times.pkl? So how do you get Perception_Test_video_info.pkl?

> Hi, I added the code I used to generate annotations of perception_test below.
> 
> Please change the paths and feel free to use them.
> 
> https://github.com/JacobChalk/TIM/blob/main/feature_extractors/make_framepickle.py

Thanks!

**Comment by JacobChalk** [comment]
Hi,

All the video info pickle file needs to contain are the video_ids and their durations. You can either download the videos from Perception Test and get their durations from the metadata, or you can approximate it by just using your maximum feature interval end time for each video. Hope this helps!

**Comment by JaesungHuh** [comment]
Hi, 

I also uploaded the script that I used for making video_info pickle file.

This is for AVE, but you could adjust it for your own dataset.

Hope this helps.

https://github.com/JacobChalk/TIM/blob/main/feature_extractors/make_videoinfo.py

**Comment by hongminglin08** [comment]
> 你好
> 
> 我还上传了用于制作 pickle 文件的脚本video_info。
> 
> 这适用于 AVE，但您可以针对自己的数据集进行调整。
> 
> 希望这有帮助。
> 
> https://github.com/JacobChalk/TIM/blob/main/feature_extractors/make_videoinfo.py

Thank you. That helps us a lot.
