### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by hongminglin08** [JacobChalk/TIM#5]
When I run the AVE code in recognition, I replace action_class with class because it doesn't appear to be in the annotation data, but I get the following error:
![image](https://github.com/JacobChalk/TIM/assets/52478955/aec4df8c-52bf-4bf4-95ae-82b409087021)
How should I modify this part of the code?

**Comment by JaesungHuh** [comment]
Hi,

Thank you for reporting this. There must be a confliction between class of epic and class of AVE.

I modified the training script and the readme for training TIM on AVE.

Please pull the repo again, and re-run. I checked the training script is running fine now.

**Comment by hongminglin08** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月20日(星期一) 晚上6:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JacobChalk/TIM] code error (Issue #5)














 
Hi,
 
Thank you for reporting this. There must be a confliction between class of epic and class of AVE.
 
I modified the training script and the code for training TIM on AVE.
 
Please pull the repo again, and re-run. I checked the training script is running fine now.
