### ISSUE TITLE
Input parameter setting

### ISSUE THREAD

**Issue by hongminglin08** [JacobChalk/TIM#6]
For the AVE dataset, I set both visual_input_dim and audio_input_dim to 1024, with the following error:
![image](https://github.com/JacobChalk/TIM/assets/52478955/5f71b629-cf92-42b7-a56c-b269a08d693f)
What is the correct input parameter?

**Comment by JacobChalk** [comment]
Hi,

This is dependent on what features you are using, would you be able to clarify what visual and audio features you are using for AVE? Based on the 2304 shape in the error, it looks like you are using Auditory SlowFast features and hence your audio input dim should be 2304.

**Comment by hongminglin08** [comment]
> Hi,
> 
> This is dependent on what features you are using, would you be able to clarify what visual and audio features you are using for AVE? Based on the 2304 shape in the error, it looks like you are using Auditory SlowFast features and hence your audio input dim should be 2304.

I'm using the audio and video features extracted by feature_extractors in your code

**Comment by JacobChalk** [comment]
In which case they are indeed Auditory SlowFast. You should use the argument: `--audio_input_dim 2304`

**Comment by hongminglin08** [comment]
> In which case they are indeed Auditory SlowFast. You should use the argument: `--audio_input_dim 2304`

This setting works, but a new error appears as follows:
![image](https://github.com/JacobChalk/TIM/assets/52478955/b7ff4ea3-ca13-4b8a-9882-652221d3acd4)

**Comment by JaesungHuh** [comment]
For using Omnivore + AuditorySlowfast features, you need to train with slightly different parameters.

See the second code in [here](https://github.com/JacobChalk/TIM/tree/main/recognition#ave). You should set the `--apply_feature_pooling False' and also change the feat_stride, feat_gap, lambda_audio, etc....

**Comment by hongminglin08** [comment]
> For using Omnivore + AuditorySlowfast features, you need to train with slightly different parameters.
> 
> See the second code in [here](https://github.com/JacobChalk/TIM/tree/main/recognition#ave). You should set the `--apply_feature_pooling False' and also change the feat_stride, feat_gap, lambda_audio, etc....

thanks.

**Comment by JaesungHuh** [comment]
Is this working now? May I close the issue?

**Comment by hongminglin08** [comment]
Okay



---Original---
From: ***@***.***&gt;
Date: Wed, May 22, 2024 22:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JacobChalk/TIM] Input parameter setting (Issue #6)




 
Is this working now? Can I close the issue?
