### ISSUE TITLE
use multiple GPUs

### ISSUE THREAD

**Issue by hongminglin08** [JacobChalk/TIM#7]
When I use 2 GPUs, the following error occurs:

![image](https://github.com/JacobChalk/TIM/assets/52478955/a2cf2584-b2e5-4239-a342-1f26a75b8b45)

Please tell me what else I need to modify if I want to use multiple GPUs.

**Comment by JacobChalk** [comment]
Hi,

Unfortunately multi-GPU is not fully supported and is very resource intensive (requiring NUM_GPUS times to cache the dataset), it could be that multiple instances of the dataset are causing memory errors. We recommend using a single GPU if possible

**Comment by hongminglin08** [comment]
> Hi,
> 
> Unfortunately multi-GPU is not fully supported and is very resource intensive (requiring NUM_GPUS times to cache the dataset), it's likely multiple instances of the dataset are causing memory errors. We recommend using a single GPU if possible

After our test, we found that there are many remaining, should not be caused by this problem
![EW}1KOIU8H1O{R35X6AC)7O](https://github.com/JacobChalk/TIM/assets/52478955/77dec4bc-1eff-473e-82f7-24774e64921b)

**Comment by JacobChalk** [comment]
Caching the dataset requires RAM, rather than VRAM in the GPU. If I remember correctly, for EPIC it required 100GB to cache the full dataset. Running for 2 GPUs will require 200GB.

However, as mentioned we do not fully support multi-gpu implementation, for our own tests we only used single GPU.

There are some args related to multi-gpu training such as `--init_method` that you may need to experiment with.

**Comment by hongminglin08** [comment]
solved



---Original---
From: "Jacob ***@***.***&gt;
Date: Mon, May 27, 2024 21:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JacobChalk/TIM] use multiple GPUs (Issue #7)




 
Caching the dataset requires RAM, rather than VRAM in the GPU. If I remember correctly, for EPIC it required 100GB to cache the full dataset. Running for 2 GPUs will require 200GB.
 
However, as mentioned we do not fully support multi-gpu implementation, for our own tests we only used single GPU

**Comment by lin-nie** [comment]
Hi, @hongminglin08, I saw you handle this problem.
May I ask whether you can run DDP on TIM codebase?
Thanks!
