### ISSUE TITLE
pretrained audio model

### ISSUE THREAD

**Issue by JMcarrot** [JacobChalk/TIM#8]
Hi!

Thanks for your work! When I post-process the features with numpy files with python utils/make_npyfiles.py, my files are like P01_01_000001.npy,not P01_01.npy. How can I get these npy files?

**Comment by JaesungHuh** [comment]
Hi!! Thank you for using our feature extraction code.

Could you first make sure you modified anything in utils/make_npyfiles.py from the original code? 

If you visit [here](https://github.com/JacobChalk/TIM/blob/3d6845c57a595843364756f99b09787fc7bf76bd/feature_extractors/auditory_slowfast/utils/make_npyfiles.py#L42), there is no index after video_id in filename.

BW,
Jaesung

**Comment by JaesungHuh** [comment]
I think I find out why you got confused. I revised the README and also the `utils/make_npyfiles.py`. 

Please visit [here](https://github.com/JacobChalk/TIM/blob/main/feature_extractors/auditory_slowfast/README.md#post-processing-epic-features) for detailed instructions.

Let me know if you have any questions.
